name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
        with:
          context: .
          build-args: |
            "ATLAS_URI=${{ secrets.ATLAS_URI }}"
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/${{ secrets.CONTAINER_NAME }}:${{ github.sha }}
         

      - name: Deploy to Azure App Services
        uses: azure/webapps-deploy@v2
        env:
          COSMOS_URI: ${{ secrets.COSMOS_URI }}
        with:
          app-name: ${{ secrets.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
          images: |
            ${{ secrets.ACR_REGISTRY }}/${{ secrets.CONTAINER_NAME }}:${{ github.sha }}
